[package]
name = "fornix"
version = "0.1.0"
authors = [""]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "main/library.rs"
crate-type = ["cdylib"]

[[bin]]
name = "main"
path = "main/main.rs"

[dependencies]